/** @type {Array<import('./types').Project>} */
export const MOCK_PROJECTS = [
  {
    id: '1',
    name: 'Rediseño de plataforma',
    description: 'Renovación completa de la UI/UX del sistema principal.',
    status: 'active',
    dueDate: '2026-06-30',
    progress: 42,
    ownerInitials: 'CP',
    tasksTotal: 24,
    tasksDone: 10,
    createdBy: 'u1',
  },
  {
    id: '2',
    name: 'App móvil iOS',
    description: 'Primera versión nativa de la aplicación para iPhone.',
    status: 'active',
    dueDate: '2026-08-15',
    progress: 18,
    ownerInitials: 'ML',
    tasksTotal: 40,
    tasksDone: 7,
    createdBy: 'u1',
  },
  {
    id: '3',
    name: 'Migración de base de datos',
    description: 'Migrar PostgreSQL 13 → 16 con zero downtime.',
    status: 'paused',
    dueDate: '2026-05-10',
    progress: 65,
    ownerInitials: 'AR',
    tasksTotal: 12,
    tasksDone: 8,
    createdBy: 'u1',
  },
  {
    id: '4',
    name: 'Campaña de marketing Q2',
    description: 'Lanzamiento digital, contenido y pauta para el segundo trimestre.',
    status: 'completed',
    dueDate: '2026-03-31',
    progress: 100,
    ownerInitials: 'JV',
    tasksTotal: 18,
    tasksDone: 18,
    createdBy: 'u1',
  },
  {
    id: '5',
    name: 'Integración con Stripe',
    description: 'Implementar pagos recurrentes y portal de facturación.',
    status: 'active',
    dueDate: '2026-07-01',
    progress: 30,
    ownerInitials: 'CP',
    tasksTotal: 15,
    tasksDone: 4,
    createdBy: 'u1',
  },
  {
    id: '6',
    name: 'Auditoría de seguridad',
    description: 'Revisión de vulnerabilidades y cumplimiento OWASP.',
    status: 'paused',
    dueDate: '2026-05-20',
    progress: 50,
    ownerInitials: 'RG',
    tasksTotal: 10,
    tasksDone: 5,
    createdBy: 'u1',
  },
];
